### ISSUE TITLE
FXML LoadException on startup

### ISSUE THREAD

**Issue by marvinmarnold** [haroldjcastillo/btc#1]
@haroldjcastillo do you know what is causing this? 

16:21:55.221 [JavaFX Application Thread] ERROR com.github.haroldjcastillo.btc.ui.SplashController - 
file:/home/marvin/code/lib/programming-challenges/HaroldCastillo/btc/btc-ui/target/btc-ui-0.0.1.jar!/fxml/orders.fxml
file:/home/marvin/code/lib/programming-challenges/HaroldCastillo/btc/btc-ui/target/btc-ui-0.0.1.jar!/fxml/main.fxml:21

javafx.fxml.LoadException: 
file:/home/marvin/code/lib/programming-challenges/HaroldCastillo/btc/btc-ui/target/btc-ui-0.0.1.jar!/fxml/orders.fxml
file:/home/marvin/code/lib/programming-challenges/HaroldCastillo/btc/btc-ui/target/btc-ui-0.0.1.jar!/fxml/main.fxml:21

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2571) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.access$2700(FXMLLoader.java:103) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader$IncludeElement.constructValue(FXMLLoader.java:1143) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3214) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3175) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3148) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3124) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3104) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3097) ~[jfxrt.jar:?]
	at com.github.haroldjcastillo.btc.ui.SplashController$SplashScreen$1.run(SplashController.java:39) ~[btc-ui-0.0.1.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$117(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$118(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71) ~[?:1.8.0_151]
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275) ~[?:1.8.0_151]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2566) ~[jfxrt.jar:?]
	... 21 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.haroldjcastillo.business.http.ExecutorService
	at com.github.haroldjcastillo.btc.ui.OrderController.loadCurrentOrders(OrderController.java:90) ~[btc-ui-0.0.1.jar:?]
	at com.github.haroldjcastillo.btc.ui.OrderController.access$100(OrderController.java:19) ~[btc-ui-0.0.1.jar:?]
	at com.github.haroldjcastillo.btc.ui.OrderController$1.run(OrderController.java:69) ~[btc-ui-0.0.1.jar:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_151]
	at com.github.haroldjcastillo.btc.ui.OrderController.initialize(OrderController.java:61) ~[btc-ui-0.0.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71) ~[?:1.8.0_151]
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275) ~[?:1.8.0_151]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2566) ~[jfxrt.jar:?]
	... 21 more

**Comment by haroldjcastillo** [comment]
Hi @marvinmarnold  maybe because there isn't connection between the http connector and Bitso rest client in this constructor https://github.com/haroldjcastillo/btc/blob/1f922be2fc081823aeec183077b0003386698e04/btc/btc-business/src/main/java/com/github/haroldjcastillo/business/http/HttpConnector.java#L28

Can you try ping the host and port if this is working ?

**Comment by marvinmarnold** [comment]
@haroldjcastillo I'm not sure what exact host and port you want me to try. Anyways, I'm able to connect to Bitso using other people's submissions and our code so I don't think the problem is with my environment. All your tests are passing. Please add a new test if there's something you want to ensure is working on my side.

**Comment by haroldjcastillo** [comment]
@marvinmarnold I have a unit test for this part and ran again, this was the results.

 https://github.com/haroldjcastillo/btc/blob/1f922be2fc081823aeec183077b0003386698e04/btc/btc-business/src/test/java/com/github/haroldjcastillo/business/test/ScheduleHttpTest.java#L15

![captura de pantalla 2018-01-30 a la s 18 44 42](https://user-images.githubusercontent.com/6539466/35599295-b00b77cc-05ed-11e8-9d5a-2cfe1df45e86.png)

In the log you can see.
```
18:43:03.427 [main] DEBUG com.github.haroldjcastillo.business.test.HttpObserver - Subscribing, disposable false
18:43:04.872 [pool-2-thread-1] INFO  com.github.haroldjcastillo.business.test.HttpObserver - {"success":true,"payload":[{"book":"btc_mxn","minimum_price":"500.00","maximum_price":"16000000.00","minimum_amount":"0.00015","maximum_amount":"500.00000000","minimum_value":"5","maximum_value":"10000000.00"},{"book":"eth_mxn","minimum_price":"10.00","maximum_price":"50000.00","minimum_amount":"0.001","maximum_amount":"100000.00000000","minimum_value":"5.00","maximum_value":"10000000.00"},{"book":"xrp_btc","minimum_price":"0.00000100","maximum_price":"5000.00000000","minimum_amount":"0.00000100","maximum_amount":"100000.00000000","minimum_value":"0.00000100","maximum_value":"100000.00000000"},{"book":"xrp_mxn","minimum_price":"0.0000100","maximum_price":"5000.00000000","minimum_amount":"0.5","maximum_amount":"500000.00000000","minimum_value":"5","maximum_value":"10000000.00000000"},{"book":"eth_btc","minimum_price":"0.00000100","maximum_price":"5000.00000000","minimum_amount":"0.00000100","maximum_amount":"1000.00000000","minimum_value":"0.00000100","maximum_value":"1000.00000000"},{"book":"bch_btc","minimum_price":"0.0001","maximum_price":"8000.00","minimum_amount":"0.0001","maximum_amount":"8000.00","minimum_value":"0.0001","maximum_value":"8000.00"},{"book":"ltc_btc","minimum_price":"0.01","maximum_price":"80000.00","minimum_amount":"0.00015","maximum_amount":"500.00000000","minimum_value":"0.001","maximum_value":"100.00"},{"book":"ltc_mxn","minimum_price":"10","maximum_price":"50000.00","minimum_amount":"0.001","maximum_amount":"100000.00000000","minimum_value":"5","maximum_value":"10000000.00"}]}
18:43:08.919 [pool-2-thread-1] INFO  com.github.haroldjcastillo.business.test.HttpObserver - {"success":true,"payload":[{"book":"btc_mxn","minimum_price":"500.00","maximum_price":"16000000.00","minimum_amount":"0.00015","maximum_amount":"500.00000000","minimum_value":"5","maximum_value":"10000000.00"},{"book":"eth_mxn","minimum_price":"10.00","maximum_price":"50000.00","minimum_amount":"0.001","maximum_amount":"100000.00000000","minimum_value":"5.00","maximum_value":"10000000.00"},{"book":"xrp_btc","minimum_price":"0.00000100","maximum_price":"5000.00000000","minimum_amount":"0.00000100","maximum_amount":"100000.00000000","minimum_value":"0.00000100","maximum_value":"100000.00000000"},{"book":"xrp_mxn","minimum_price":"0.0000100","maximum_price":"5000.00000000","minimum_amount":"0.5","maximum_amount":"500000.00000000","minimum_value":"5","maximum_value":"10000000.00000000"},{"book":"eth_btc","minimum_price":"0.00000100","maximum_price":"5000.00000000","minimum_amount":"0.00000100","maximum_amount":"1000.00000000","minimum_value":"0.00000100","maximum_value":"1000.00000000"},{"book":"bch_btc","minimum_price":"0.0001","maximum_price":"8000.00","minimum_amount":"0.0001","maximum_amount":"8000.00","minimum_value":"0.0001","maximum_value":"8000.00"},{"book":"ltc_btc","minimum_price":"0.01","maximum_price":"80000.00","minimum_amount":"0.00015","maximum_amount":"500.00000000","minimum_value":"0.001","maximum_value":"100.00"},{"book":"ltc_mxn","minimum_price":"10","maximum_price":"50000.00","minimum_amount":"0.001","maximum_amount":"100000.00000000","minimum_value":"5","maximum_value":"10000000.00"}]}
18:43:13.967 [pool-2-thread-1] INFO  com.github.haroldjcastillo.business.test.HttpObserver - {"success":true,"payload":[{"book":"btc_mxn","minimum_price":"500.00","maximum_price":"16000000.00","minimum_amount":"0.00015","maximum_amount":"500.00000000","minimum_value":"5","maximum_value":"10000000.00"},{"book":"eth_mxn","minimum_price":"10.00","maximum_price":"50000.00","minimum_amount":"0.001","maximum_amount":"100000.00000000","minimum_value":"5.00","maximum_value":"10000000.00"},{"book":"xrp_btc","minimum_price":"0.00000100","maximum_price":"5000.00000000","minimum_amount":"0.00000100","maximum_amount":"100000.00000000","minimum_value":"0.00000100","maximum_value":"100000.00000000"},{"book":"xrp_mxn","minimum_price":"0.0000100","maximum_price":"5000.00000000","minimum_amount":"0.5","maximum_amount":"500000.00000000","minimum_value":"5","maximum_value":"10000000.00000000"},{"book":"eth_btc","minimum_price":"0.00000100","maximum_price":"5000.00000000","minimum_amount":"0.00000100","maximum_amount":"1000.00000000","minimum_value":"0.00000100","maximum_value":"1000.00000000"},{"book":"bch_btc","minimum_price":"0.0001","maximum_price":"8000.00","minimum_amount":"0.0001","maximum_amount":"8000.00","minimum_value":"0.0001","maximum_value":"8000.00"},{"book":"ltc_btc","minimum_price":"0.01","maximum_price":"80000.00","minimum_amount":"0.00015","maximum_amount":"500.00000000","minimum_value":"0.001","maximum_value":"100.00"},{"book":"ltc_mxn","minimum_price":"10","maximum_price":"50000.00","minimum_amount":"0.001","maximum_amount":"100000.00000000","minimum_value":"5","maximum_value":"10000000.00"}]}
18:43:19.103 [pool-2-thread-1] INFO  com.github.haroldjcastillo.business.test.HttpObserver - {"success":true,"payload":[{"book":"btc_mxn","minimum_price":"500.00","maximum_price":"16000000.00","minimum_amount":"0.00015","maximum_amount":"500.00000000","minimum_value":"5","maximum_value":"10000000.00"},{"book":"eth_mxn","minimum_price":"10.00","maximum_price":"50000.00","minimum_amount":"0.001","maximum_amount":"100000.00000000","minimum_value":"5.00","maximum_value":"10000000.00"},{"book":"xrp_btc","minimum_price":"0.00000100","maximum_price":"5000.00000000","minimum_amount":"0.00000100","maximum_amount":"100000.00000000","minimum_value":"0.00000100","maximum_value":"100000.00000000"},{"book":"xrp_mxn","minimum_price":"0.0000100","maximum_price":"5000.00000000","minimum_amount":"0.5","maximum_amount":"500000.00000000","minimum_value":"5","maximum_value":"10000000.00000000"},{"book":"eth_btc","minimum_price":"0.00000100","maximum_price":"5000.00000000","minimum_amount":"0.00000100","maximum_amount":"1000.00000000","minimum_value":"0.00000100","maximum_value":"1000.00000000"},{"book":"bch_btc","minimum_price":"0.0001","maximum_price":"8000.00","minimum_amount":"0.0001","maximum_amount":"8000.00","minimum_value":"0.0001","maximum_value":"8000.00"},{"book":"ltc_btc","minimum_price":"0.01","maximum_price":"80000.00","minimum_amount":"0.00015","maximum_amount":"500.00000000","minimum_value":"0.001","maximum_value":"100.00"},{"book":"ltc_mxn","minimum_price":"10","maximum_price":"50000.00","minimum_amount":"0.001","maximum_amount":"100000.00000000","minimum_value":"5","maximum_value":"10000000.00"}]}

```

**Comment by haroldjcastillo** [comment]
Sorry for answer late, I don't found the mistake, if we can fix it, I will be glad to do it, thanks 

![image](https://user-images.githubusercontent.com/6539466/35599797-30c74790-05f0-11e8-9352-415e5f7298b2.png)
